# Generated by Django 5.1.1 on 2024-09-15 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='teacherId',
            field=models.IntegerField(default=0),
        ),
    ]
