# Generated by Django 5.1.1 on 2024-09-15 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_add_teacher_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='teacherId',
            new_name='blog_id',
        ),
        migrations.AddField(
            model_name='blog',
            name='desc',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='blog',
            name='title',
            field=models.CharField(default='', max_length=60),
        ),
    ]
