# Generated by Django 5.1.1 on 2024-09-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_add_porduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('FR', 'Fruits'), ('ML', 'Milk'), ('CK', 'Cake'), ('RC', 'Rice')], max_length=2),
        ),
    ]
